version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo apt-get -y -qq install awscli
      - run:
          name: Send to S3
          command: ls -a
