version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install awscli
          command: pip install awscli
      - run:
          name: Send to S3
          command: aws s3 sync /var/www/html/testes s3://rd-marketing-tools --delete
